# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='id',
        ),
        migrations.AlterField(
            model_name='player',
            name='pid',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Player ID'),
        ),
    ]
